name: GitVersion

on:
  push:
    branches: [ ]

  workflow_dispatch:

jobs:
  gitVersion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
        
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Determine Version
        id: gitversion
        #uses: gittools/actions/gitversion/execute@v0.9.7
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
          echo "SemVer: ${{ steps.gitversion.outputs.VERSION }}"
