name: Publish To Nuget

on:
  workflow_dispatch:

jobs:
  publish_to_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
        
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Determine Version
        id: gitversion
        #uses: gittools/actions/gitversion/execute@v0.9.7
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Display SemVer
        run: |
          echo "SemVer: $GITVERSION_SEMVER"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
          echo "SemVer: ${{ steps.gitversion.outputs.VERSION }}"
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.x"
          
      - name: Build solution and generate NuGet package
        run: |
          dotnet pack -c Release -o out -p:PackageVersion=${{ steps.gitversion.outputs.VERSION }}
          
      - name: Push HttpClient to GitHub registry
        run: dotnet nuget push ./out/SugarChat.Net.Client.${{ steps.gitversion.outputs.VERSION }}.nupkg --skip-duplicate --no-symbols true -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
